!include configs/envs/arm_env.yaml

DEBUG: 0

MAX_STEPS: null

KINECT2:
  DEPTH:
    HEIGHT: 424
    WIDTH: 512
    DISTANCE: 1.0
    INTRINSICS: [372.66, 0., 241.20, 0., 368.62, 214.19, 0., 0., 1.]
    TRANSLATION: [0., -0.6, 1.5]
    ROTATION: [-3.1415, 0, 1.5708]
    INTRINSICS_NOISE: null
    TRANSLATION_NOISE: null
    ROTATION_NOISE: null
    #CROP: [150, 0, 424, 512]

OBSERVATION:
  # Choose between `depth` and `point_cloud`.
  TYPE: 'depth'

ACTION:
  # Choose between `IMAGE`(in image space) and `CUBOID`(in a 3D cuboid region).
  TYPE: 'IMAGE'

  # The `CUBOID` defines a cuvoid region for the grasping center.
  CUBOID:
    LOW: [0.30, -0.50, 0.02]
    HIGH: [0.90, 0.50, 0.12]

ARM:
  # Move the arm out of the table.
  OFFSTAGE_POSITIONS: [0, 0, 0, 0, 0, 0]

  # Move the arm above the table.
  OVERHEAD_POSITIONS: [0, 0, 0, 0, 0, 0]

  # The safe height to move the gripper above the table.
  GRIPPER_SAFE_HEIGHT: 0.4

  # The distance from the the end effector to the center of finger tips.
  FINGER_TIP_OFFSET: 0.125

  # If move to the overhead position after grasping.
  MOVE_TO_OVERHEAD_AFTER_GRASP: 1
    

SIM:
  ARM:
    CONFIG: 'configs/robots/franka_panda_gripper.yaml'
    ROBOT: 'franka_panda_free'
    POSE: [[0, 0, -0.1], [0, 0, 0]]
    ARM_NAME: 'franka_panda'

  GROUND:
    PATH: 'sim/envs/arm_env/planes/plane.urdf'
    POSE: [[0, 0, -0.9], [0, 0, 0]]

  WALL:
    USE: 0
    PATH: 'sim/envs/arm_env/wall.urdf'
    POSE: [[0, 0, -0.9], [0, 0, 0]]

  TABLE:
      PATH: 'sim/envs/arm_env/tables/table_grasp.urdf'
      POSE: [[0.6, 0, -1.0], [0, 0, 0]]
      HEIGHT_RANGE: [0.9, 0.9]

  GRASPABLE:
    PATHS: [
      'urdf_centered_test/*/*.urdf',
    ]
    POSE:
      # X: [0, 0]
      # Y: [0, 0]
      X: [-0.1, 0.1]
      Y: [-0.1, 0.1]
      Z: 0.3
      # ROLL: [0, 0]
      # PITCH: [0, 0]
      # YAW: [0, 0]
      ROLL: [-3.14, 3.14]
      PITCH: [-1.57, 1.57]
      YAW: [-3.14, 3.14]
    SCALE: [1.2, 1.2]
    USE_RANDOM_SAMPLE: 0
    RESAMPLE_N_EPISODES: 1

  MAX_ACTION_STEPS: 4000
