GRIPPER_WIDTH: 0.06

SAMPLER:
  FRICTION_COEF: 1.0
  DEPTH_GRAD_THRESH: 0.001
  DEPTH_GRAD_GAUSSIAN_SIGMA: 1.0
  DOWNSAMPLE_RATE: 1
  MAX_REJECTION_SAMPLES: 8000

  CROP: [120, 0, 424, 512]
  MIN_DIST_FROM_BOUNDARY: 25
  MIN_GRASP_DIST: 2.5
  ANGLE_DIST_WEIGHT: 5.0

  DEPTH_SAMPLES_PER_GRASP: 1
  DEPTH_SAMPLE_WINDOW_HEIGHT: 1
  DEPTH_SAMPLE_WINDOW_WIDTH: 1
  MIN_DEPTH_OFFSET: 0.015
  MAX_DEPTH_OFFSET: 0.05
